TARGET=graphicsHW
OBJS1= graphicsHW1.o
CC=g++
LDFLAGS=-lGL -lglut -lGLU
# INCLUDES =
# CLFAGS=$(INCLUDES)
#

hw1: $(OBJS1)
	$(CC) -o $(TARGET)1 $(OBJS1) $(LDFLAGS)

run1: 
	./$(TARGET)1

clean:
	rm $(TARGET)*.o $(OBJS1)
